import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('배포용 매뉴얼', () => {
  it('사용자·운영자 HTML이 주요 안내를 담는다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(user).toContain('한 턴의 순서');
    expect(user).toContain('지금 구현된 것');
    expect(user).toContain('첫 판 따라하기');
    expect(user).toContain('케이스북');
    expect(user).toContain('안정형');
    expect(user).toContain('70%');
    expect(user).toContain('C18');
    expect(user).toContain('진행');
    expect(user).toContain('보류');
    expect(user).toContain('한도까지');
    expect(user).toContain('C21');
    expect(user).toContain('지금 판에 바로');
    expect(user).toContain('지금 판에 반영');
    expect(user).toContain('이 브라우저에 저장');
    expect(user).toContain('예금·채권 매수는 됩니다');
    expect(user).toContain('정산 요약');
    expect(user).toContain('C22');
    expect(user).toContain('3별의 성향 정렬');
    expect(user).toContain('미지급 생활비');
    expect(user).toContain('C19');
    expect(user).toContain('C20');
    expect(user).toContain('도착 칸이');
    expect(user).toContain('목표에 가까워진 적립가');
    expect(user).toContain('목표의 95%');
    expect(user).toContain('C23');
    expect(user).toContain('리밸런싱 목표 위험비중');
    expect(operator).toContain('구현된 기능');
    expect(operator).toContain('QA 케이스 매트릭스');
    expect(operator).toContain('vercel');
    expect(operator).toContain('2609-pension-monopoly.vercel.app');
    expect(operator).toContain('policy-rules.json');
    expect(operator).toContain('pages.yml');
    expect(operator).toContain('비중을 더 키우지 않는');
    expect(operator).toContain('Q17');
    expect(operator).toContain('Q18');
    expect(operator).toContain('Q19');
    expect(operator).toContain('Q20');
    expect(operator).toContain('Q21');
    expect(operator).toContain('nearGoalRate');
    expect(user).toContain('대기자금은 0원');
    expect(user).toContain('먼저 납입하기');
    expect(user).toContain('위험자산 충격');
    expect(operator).toContain('goalMonthly');
    expect(operator).toContain('Q22');
    expect(operator).toContain('Q23');
    expect(user).toContain('교육용 가상 금리');
    expect(user).toContain('2~3회');
    expect(user).toContain('다음 턴 신호');
    expect(user).toContain('신호는 예측이 아니라');
    expect(user).toContain('C24');
    expect(user).toContain('C25');
    expect(user).not.toContain('3~10턴 사이 2회');
    expect(operator).toContain('market-shocks.json');
    expect(user).toContain('C27');
    expect(user).toContain('C28');
    expect(user).toContain('캐릭터 표시');
    expect(user).toContain('기본 끔');
    expect(user).toContain('가장 아슬아슬했던 턴');
    expect(operator).toContain('Q30');
    expect(operator).toContain('Q32');
    expect(operator).toContain('Q35');
    expect(operator).toContain('Q36');
    expect(operator).toContain('token3d.ts');
    expect(user).toContain('말 모양');
    expect(operator).toContain('settings.characters');
    expect(operator).toContain('avatars.ts');
    expect(operator).toContain('sound.ts');
    expect(operator).toContain('regime-engine.ts');
    expect(operator).toContain('balance-gate');
    expect(operator).toContain('Q24');
    expect(operator).toContain('Q25');
    expect(operator).toContain('Q26');
    expect(user).toContain('속보 카드');
    expect(user).toContain('칸 설명 보기');
    expect(user).toContain('정산 장면');
    expect(user).toContain('목표 게이지');
    expect(user).toContain('C26');
    expect(operator).toContain('news-flash.ts');
    expect(operator).toContain('hud.ts');
    expect(operator).toContain('Q27');
    expect(operator).toContain('Q28');
    expect(operator).toContain('Q29');
  });

  it('2026-09-06 현행화: 구현 기준일·운영 태그·모듈 목록·기능 목록이 최신이다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(operator).toContain('구현 기준 2026-09-10');
    expect(operator).not.toContain('구현 기준 2026-08-17');
    expect(operator).not.toContain('2026-08-17)');
    expect(operator).toContain('prod-2026-09-06-token-3d');
    expect(operator).toContain('운영 태그와 되돌리기');
    expect(operator).toContain('Promote');
    expect(operator).toContain('git revert -m 1');
    expect(operator).toContain('board.ts');
    expect(operator).toContain('dice.ts');
    expect(operator).toContain('market-view.ts');
    expect(operator).toContain('settlement-engine.ts');
    expect(operator).toContain('2.5D 말');
    expect(operator).toContain('연출 코어');
    expect(operator).toContain('회귀 359개');
    expect(operator).not.toContain('회귀 316개');
    expect(operator).not.toContain('회귀 231개');
    expect(operator).toContain('Q1~Q61');
    expect(operator).not.toContain('Q1~Q54');
    expect(operator).not.toContain('Q1~Q46');
    expect(operator).not.toContain('Q1~Q45');
    expect(operator).not.toContain('Q1~Q16');
    expect(operator).not.toContain('Q1~Q36');
    expect(user).toContain('구현 기준 2026-09-10');
    expect(user).not.toContain('구현 기준 2026-08-17');
    expect(user).toContain('12턴 IRP 곡선');
    expect(user).toContain('효과음 10종');
    expect(user).not.toContain('효과음 9종');
    expect(user).toContain('설정(동작 줄이기·캐릭터 표시·효과음·"그대로 둔 나" 비교·애니메이션 2× 빠르게·정산 자동 진행·정산 「자세히」 펼침)');
  });

  it('묶음 A 현행화: 시장 먼저 순서·칸 효과·환급·행동 2회·고스트가 두 매뉴얼에 있다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    // 사용자: 순서·규칙
    expect(user).toContain('시장이 먼저 움직입니다');
    expect(user).toContain('내 IRP에 반영');
    expect(user).toContain('도착 칸 효과');
    expect(user).toContain('연말정산 칸을 지날 때');
    expect(user).toContain('환급 대기');
    expect(user).toContain('행동 1/2 하기');
    expect(user).toContain('스포트라이트');
    expect(user).toContain('은퇴 전망대');
    expect(user).toContain('그대로 둔 나');
    expect(user).toContain('판단의 값어치');
    expect(user).toContain('고스트 격파');
    expect(user).toContain('턴 시작 → 시장 반영 → 내 행동 후');
    expect(user).not.toContain('아직 잔고에는 안 들어갑니다');
    expect(user).not.toContain('거래 없이 이번 턴 시장만 반영합니다');
    for (const id of ['C30', 'C31', 'C32', 'C33', 'C34', 'C35', 'C36', 'C37']) expect(user).toContain(`${id}.`);
    // 운영자: 모듈·저장·QA·게이트·절차
    expect(operator).toContain('tile-effects.ts');
    expect(operator).toContain('ghost.ts');
    expect(operator).toContain('tile-effects-view.ts');
    expect(operator).toContain('settings.ghost');
    expect(operator).toContain('버전 4');
    expect(operator).toContain('pendingTaxCredit');
    expect(operator).toContain('newsChaser');
    expect(operator).toContain('turn-order.test.ts');
    expect(operator).toContain('OUTLOOK_FORKS');
    expect(operator).toContain('EXTRA_LIFE_EVENT_CAP');
    expect(operator).toContain('prod-2026-09-06-bundle-a');
    expect(operator).toContain('필수 절차');
    for (const id of ['Q37', 'Q38', 'Q39', 'Q40', 'Q41', 'Q42', 'Q43', 'Q44', 'Q45']) expect(operator).toContain(`<td>${id}</td>`);
    expect(operator).not.toContain('브리핑 → 생활사건 → 행동 1회 → 정산');
    expect(operator).not.toContain('WebAudio 합성 8종');
  });

  it('매도·교체 선택 보정 핫픽스: 두 매뉴얼이 규칙과 QA 케이스를 담는다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(user).toContain('10만 원 이상 보유한 상품만');
    expect(user).toContain('첫 보유 상품으로 자동으로 넘어갑니다');
    expect(user).toContain('위험 상품을 안전자산으로 옮기는 가장 빠른 길');
    expect(user).toContain('C38.');
    expect(operator).toContain('action-form.ts');
    expect(operator).toContain('pickHeldProduct');
    expect(operator).toContain('tradeBlockReason');
    expect(operator).toContain('<td>Q46</td>');
    expect(operator).toContain('prod-2026-09-06-sell-switch-fix');
  });

  it('묶음 B 현행화: 디폴트옵션·사건 3지선다·퀴즈·수령 방식·결과 서사·이정표가 두 매뉴얼에 있다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    // 사용자: 규칙·화면
    expect(user).toContain('디폴트옵션 지정');
    expect(user).toContain('이 옵션으로 시작');
    expect(user).toContain('지정 안 함');
    expect(user).toContain('현금 유지 지시');
    expect(user).toContain('원리금보장형');
    expect(user).toContain('사전지정운용');
    expect(user).toContain('선택지 3개');
    expect(user).toContain('IRP 예금 현금화 후 중도인출');
    expect(user).toContain('IRP로 이전');
    expect(user).toContain('지금 받기(일시 수령)');
    expect(user).toContain('다른 선택이었다면');
    expect(user).toContain('자녀 학자금');
    expect(user).toContain('이직 · 퇴직금 정산');
    expect(user).toContain('퀴즈와 배운 것');
    expect(user).toContain('마무리 퀴즈 최대 3문항');
    expect(user).toContain('이번엔 건너뛰기');
    expect(user).toContain('오답은 벌점');
    expect(user).toContain('수령 방식');
    expect(user).toContain('연금(20년)');
    expect(user).toContain('일시금');
    expect(user).toContain('5.5%');
    expect(user).toContain('16.5%');
    expect(user).toContain('계좌 재원별로 달라집니다');
    expect(user).toContain('수령 방식 바꾸기');
    expect(user).toContain('마무리로 · 퀴즈와 수령 방식');
    expect(user).toContain('잠긴 별 이유');
    expect(user).toContain('처방');
    expect(user).toContain('이정표 배너');
    expect(user).toContain('낙폭 12% 초과');
    expect(user).toContain('기본 4 + 퀴즈 정답×2(최대 8)');
    expect(user).toContain('배운 것');
    expect(user).toContain('학습 카드 도감(20장)');
    expect(user).toContain('효과음 10종');
    expect(user).not.toContain('12턴을 끝낸 뒤에는 이 창 없이 결과 리포트로 갑니다');
    expect(user).not.toContain('생활사건 중도인출 버튼이 거절된다');
    for (const id of ['C39', 'C40', 'C41', 'C42', 'C43', 'C44', 'C45', 'C46', 'C47', 'C48']) expect(user).toContain(`${id}.`);
    // 운영자: 모듈·데이터·저장·QA·게이트·태그
    expect(operator).toContain('prod-2026-09-06-bundle-b');
    expect(operator).toContain('life-engine.ts');
    expect(operator).toContain('default-option.ts');
    expect(operator).toContain('quiz-engine.ts');
    expect(operator).toContain('milestones.ts');
    expect(operator).toContain('life-view.ts');
    expect(operator).toContain('quiz-view.ts');
    expect(operator).toContain('payout-view.ts');
    expect(operator).toContain('default-option-view.ts');
    expect(operator).toContain('default-options.json');
    expect(operator).toContain('pensionTaxRate');
    expect(operator).toContain('lumpSumTaxRate');
    expect(operator).toContain('payoutFactor');
    expect(operator).toContain('applyDefaultOption');
    expect(operator).toContain('lifeChoicesFor');
    expect(operator).toContain('eligibleWithdrawal');
    expect(operator).toContain('pickQuizCard');
    expect(operator).toContain('FINAL_QUIZ_MAX');
    expect(operator).toContain('KNOWLEDGE_CAPS');
    expect(operator).toContain('starLockReason');
    expect(operator).toContain('shortfallPlan');
    expect(operator).toContain('stampMilestones');
    expect(operator).toContain('isUrgent');
    expect(operator).toContain('STICKY_MODALS');
    expect(operator).toContain('버전 5');
    expect(operator).toContain('<td>defaultOption</td>');
    expect(operator).toContain('WebAudio 합성 10종');
    expect(operator).not.toContain('WebAudio 합성 9종');
    expect(operator).toContain('묶음 B 게이트 측정');
    expect(operator).toContain('payout.test.ts');
    expect(operator).toContain('life-choices.test.ts');
    expect(operator).toContain('quiz.test.ts');
    expect(operator).toContain('narrative.test.ts');
    expect(operator).not.toContain('퀴즈(묶음 B)로 교체 예정');
    for (const id of ['Q47', 'Q48', 'Q49', 'Q50', 'Q51', 'Q52', 'Q53', 'Q54']) expect(operator).toContain(`<td>${id}</td>`);
  });

  it('퀴즈 문항은 제도·상품·시장 상식이고 보드 규칙을 묻지 않는다고 매뉴얼이 적는다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(user).toContain('퇴직연금 제도, 운용 상품, 시장이 흔들릴 때의 태도');
    expect(operator).toContain('퀴즈 질문·선택지에는 턴·속보·게임');
  });

  it('묶음 C 현행화: 턴 리듬(그대로 직결·정산 접기/자동 진행·속도 2×·후반 가속)·업적·컬렉션·주간 시드가 두 매뉴얼에 있다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    // 사용자: 리듬
    expect(user).toContain('턴 리듬');
    expect(user).toContain('확인 창 없음');
    expect(user).toContain('애니메이션 2× 빠르게');
    expect(user).toContain('정산 자동 진행');
    expect(user).toContain('후반 가속');
    expect(user).toContain('사건 N회 남음');
    expect(user).toContain('자세히');
    // 사용자: 업적·컬렉션·주간 시드
    expect(user).toContain('업적 · 컬렉션 · 주간 시드');
    expect(user).toContain('업적 12개');
    expect(user).toContain('캐릭터 컬렉션');
    expect(user).toContain('이번 주 시드로 도전');
    expect(user).toContain('weekly-');
    expect(user).toContain('결과 복사');
    expect(user).toContain('업적은 점수·별에 아무 영향이 없습니다');
    expect(user).toContain('한 판이 너무 길어요');
    expect(user).not.toContain('결과 공유 이미지');
    for (const id of ['C49', 'C50', 'C51', 'C52', 'C53', 'C54', 'C55']) expect(user).toContain(`${id}.`);
    // 운영자: 기능·모듈·상수·저장·QA·게이트·태그
    expect(operator).toContain('prod-2026-09-06-bundle-c');
    expect(operator).not.toContain('태그 <code>prod-2026-09-06-bundle-b</code>)');
    expect(operator).toContain('턴 리듬 다이어트');
    expect(operator).toContain('achievements.ts');
    expect(operator).toContain('achievements-view.ts');
    expect(operator).toContain('PlayRecord');
    expect(operator).toContain('speedScale');
    expect(operator).toContain('scenePace');
    expect(operator).toContain('LATE_GAME_TURN');
    expect(operator).toContain('canAutoSettle');
    expect(operator).toContain('AUTO_SETTLE_MS');
    expect(operator).toContain('remainingLifeEvents');
    expect(operator).toContain('holdMenuNote');
    expect(operator).toContain('GHOST_CRUSH_GAP');
    expect(operator).toContain('CALM_SEAS_DRAWDOWN');
    expect(operator).toContain('weeklySeed');
    expect(operator).toContain('resultShareText');
    expect(operator).toContain('버전 6');
    for (const field of ['settings.speed', 'settings.autoSettle', 'settings.settleExpanded', 'achievements', 'collection']) expect(operator).toContain(`<td>${field}</td>`);
    expect(operator).toContain('묶음 C 업적 게이트 측정');
    expect(operator).toContain('rhythm.test.ts');
    expect(operator).toContain('achievements.test.ts');
    expect(operator).toContain('bundle-c-views.test.ts');
    for (const id of ['Q55', 'Q56', 'Q57', 'Q58', 'Q59', 'Q60', 'Q61']) expect(operator).toContain(`<td>${id}</td>`);
  });

  it('운영자 매뉴얼 표는 칸 너비 클래스와 가로 스크롤 그릇을 쓴다', () => {
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    const css = readFileSync('public/manuals.css', 'utf8');
    expect(operator).toContain('class="wrap wide"');
    expect(operator).toContain('table-scroll');
    expect(operator).toContain('cols-status');
    expect(operator).toContain('cols-path');
    expect(css).toContain('word-break: keep-all');
    expect(css).toContain('table-layout: fixed');
  });

  it('제출 핸드오프 HTML이 실행 프롬프트·패키지·소스 목록을 담고 두 매뉴얼이 링크한다', () => {
    const page = readFileSync('public/submission-handoff.html', 'utf8');
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(page).toContain('실행가능한 상태를 만드는 프롬프트');
    expect(page).toContain('필요한 패키지');
    expect(page).toContain('소스코드 목록');
    expect(page).toContain('npm ci');
    expect(page).toContain('prod-2026-09-07-quiz-pension');
    expect(page).toContain('devDependencies');
    expect(page).toContain('game-engine.ts');
    expect(page).toContain('vite');
    expect(page).toContain('.env를 만들지 말 것');
    expect(user).toContain('submission-handoff.html');
    expect(operator).toContain('submission-handoff.html');
  });

  it('다이어그램 5장이 배포 폴더에 있고 운영자 매뉴얼이 링크한다', () => {
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(operator).toContain('href="./diagrams/"');
    const index = readFileSync('public/diagrams/index.html', 'utf8');
    for (const name of ['architecture', 'turn-workflow', 'seed-dataflow', 'game-lifecycle', 'action-sequence']) {
      expect(index).toContain(`./${name}.html`);
      const html = readFileSync(`public/diagrams/${name}.html`, 'utf8');
      expect(html).toContain('<svg');
      expect(JSON.parse(readFileSync(`docs/diagrams/${name}.json`, 'utf8')).meta.quality_profile).toBe('showcase');
    }
  });
});
