import { writeFileSync } from 'node:fs';
import { learningCards, balanceConfig } from '../src/data/content';
import { CONTENT_VERSION, CONTENT_REVIEWED_AT, LEARNING_RULES, SOURCES } from '../src/data/learning-rules';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const page=(title:string,body:string)=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><link rel="stylesheet" href="./manuals.css"><style>main{max-width:960px;margin:auto;padding:24px}body{font:17px/1.8 system-ui;background:#f8f8f1;color:#173b39}section,article{margin:24px 0;padding:24px;background:white;border:1px solid #ccd8d1;border-radius:16px}h1,h2{line-height:1.4}a{color:#185c57}nav{display:flex;gap:16px;flex-wrap:wrap}.rule-kind{font-weight:700;color:#215c75}summary{cursor:pointer;font-weight:700}code{overflow-wrap:anywhere}table{width:100%}td,th{padding:10px;text-align:left;vertical-align:top}@media(max-width:480px){main{padding:16px}section,article{padding:16px}}</style></head><body><main><nav><a href="./">게임으로</a><a href="./user-manual.html">사용자 안내</a><a href="./operator-manual.html">운영자 안내</a><a href="./learning-guide.html">공통 학습 자료</a></nav><h1>${title}</h1>${body}</main></body></html>`;
const ruleBody=Object.entries(LEARNING_RULES).map(([id,r])=>`<article id="rule-${id}"><h2>${r.title}</h2><p class="rule-kind">실제 제도·일반 원리</p><p>${esc(r.principle)}</p><p class="rule-kind">이 판의 가정</p><p>${esc(r.assumption)}</p><ul>${r.sources.map(id=>{const s=SOURCES[id];return `<li><a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)}</a> · ${esc(s.scope)}</li>`}).join('')}</ul><small>내용 기준 ${CONTENT_VERSION} · 확인 ${CONTENT_REVIEWED_AT}</small></article>`).join('');
const cardBody=learningCards.map(c=>`<article id="${c.id}"><h2>${esc(c.title)}</h2><p><b>학습목표</b> ${esc(c.learningObjective??c.key)}</p><p>${esc(c.detail)}</p><p><b>실제 제도·일반 원리</b> ${esc(c.actualPrinciple??'')}</p><p><b>이 판의 가정</b> ${esc(c.gameAssumption??'')}</p><details><summary>${esc(c.quiz.q)}</summary><ol>${c.quiz.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol><p>정답 ${c.quiz.answer+1}: ${esc(c.quiz.why)}</p></details><a href="#rule-${c.ruleId}">공통 기준·공식 근거 확인</a></article>`).join('');
writeFileSync('public/learning-guide.html',page('연금로드 학습 명세 · 25문항',`<p>실제 제도와 이 판의 가정을 구분합니다. 일반 투자 원리의 해외 자료를 한국 퇴직연금 법규의 근거로 사용하지 않습니다.</p><nav><a href="#rules">공통 규칙</a><a href="#quizzes">25문항</a></nav><h2 id="rules">공통 규칙</h2>${ruleBody}<h2 id="quizzes">25문항과 해설</h2>${cardBody}`));
const section=(id:string,title:string,body:string)=>`<section id="${id}"><h2>${title}</h2>${body}</section>`;
const user=
section('start','1. 성향을 확인하고 시작하기',`<p>시작 준비에서 투자자성향을 먼저 확인하세요. 처음에는 교육용 5문항을 풀고, 저장된 성향이 있으면 유지하거나 다시 진단할 수 있습니다. 캐릭터 외형은 성향과 별개입니다.</p><p>다음 화면에서 성향에 맞는 디폴트옵션을 선택합니다. 「성향 추천」은 안내이고 「현재 선택됨」이 실제 선택입니다. <b>사전지정만으로 매수되지 않습니다.</b> 지정하지 않고 직접 운용할 수도 있습니다.</p><p>최종 시작 버튼을 눌러야 새 판이 만들어집니다. 시작 준비의 X·뒤로 가기는 자산과 기존 진행을 바꾸지 않습니다. 주간 도전은 성향·미션·목표가 정해져 있어 먼저 확인합니다.</p><p>미션·성향·목표는 시작 후 고정합니다. 다른 성향으로 플레이하려면 다음 새 판 준비에서 바꾸세요. 「이어서 플레이」는 기존 판의 조건을 유지합니다.</p>`)+
section('turn','2. 한 턴: 이동 → 판단 → 정산',`<ol><li>주사위 합만큼 이동하고 시장이 내 보유분에 먼저 반영됩니다.</li><li>생활사건이 있으면 선택한 뒤 운용지시를 합니다. 일반 턴은 행동 1회, 운용지시 칸은 2회입니다.</li><li>정산에서 시장 손익·외부 입출금·매매 및 정산 변화를 읽습니다. 설명을 펼치거나 포트폴리오를 확인하는 것은 행동이 아닙니다.</li></ol><p>퀴즈는 정산에서 선택해서 풀 수 있습니다. 건너뛰어도 자산·세금·행동 횟수에 불이익은 없고, 정답은 지식 점수에 반영됩니다. 동작 줄이기·빠른 연출·자동 정산은 설정에서 선택합니다.</p>`)+
section('money','3. 생활자금과 IRP 대기자금',`<p><b>생활자금</b>은 생활비를 내는 돈, <b>IRP 대기자금</b>은 계좌 안에서 상품을 매수할 돈입니다. 펀드 환매 대금은 결제 전까지 주문 가능 현금이 아닙니다.</p><p>새 판의 개인 추가납입은 <b>턴 합계 ${balanceConfig.contributionPerTurnLimit/10000}만원</b>입니다. 행동 2회와 보너스 납입도 합산합니다. 미사용 한도는 이월하지 않으며 퇴직급여 이전은 별도입니다.</p><p>한 판 합산 납입 한도·세액공제 대상 한도·턴 진행용 한도는 서로 다릅니다. 공제 효과는 연말정산 칸에서 생활자금으로 돌아오는 게임 가정입니다. <a href="./learning-guide.html#rule-contribution">실제 한도와 공제 조건</a>.</p>`)+
section('trade','4. 매수·매도·교체·리밸런싱',`<p>운용 카드에서 상품·금액을 고른 뒤 미리보기의 자금 출처, 비용, 접수·가격확정·결제 시간을 확인하고 실행하세요. 접수 성공은 행동 1회이며 조회·X 취소·입력 변경은 0회입니다.</p><p>펀드는 접수 → 다음 턴 가격확정 → 그다음 턴 결제입니다. 예금·ETF는 게임에서 즉시 처리합니다. 교체와 리밸런싱은 매도 결제 뒤 매수가 이어질 수 있습니다. 실제 영업일을 재현한 일정은 아닙니다.</p><p>일반 운용은 직접 보유분, 옵션 옵트아웃은 옵션 보유분을 다룹니다. 지정·보유·미결제 주문을 구분하세요. 옵션 환매 후 대금은 IRP 안에 남습니다.</p><p>만기 예금은 약정 종료와 재운용 대기를 표시합니다. 자동으로 재투자하지 않으므로 기존 운용지시에서 가능한 매도·교체 또는 옵션 환매 경로를 검토하세요.</p><p>「포트폴리오 확인」은 운용 창 맨 아래입니다. 돌아오면 선택한 입력과 위치를 이어갑니다. 운용 취소는 X를 사용하고 남은 행동을 마칠 때는 「이번엔 그대로」를 누릅니다.</p>`)+
section('life','5. 생활사건과 중도인출',`<p>선택지에서 지급할 생활자금·남을 미지급 생활비를 먼저 확인하세요. 일반 생활비가 부족하다고 IRP를 자동 인출하지 않습니다. 허용되지 않는 인출은 사유를 안내합니다.</p><p>법정 사유에 따른 중도인출과 IRP 안 상품 매도는 다릅니다. 미지급 생활비는 이후 생활자금 유입에서 지급하는 게임 처리입니다. <a href="./learning-guide.html#rule-withdrawal">인출 조건과 게임 가정</a>.</p>`)+
section('finish','6. 12턴 마무리와 다시 도전',`<p>12턴 마지막 주문은 <b>추가 시장·급여 없이 마감 정산</b>에서 끝냅니다. 미결제 주문을 정리한 후 연금과 일시금을 비교합니다.</p><p>목표용 월 환산액은 목표 판정용입니다. 실제 수령 비교는 재원별 세금을 적용한 세후 총액과 평균 월액을 보세요. 20년 분할은 게임 가정이며 특정 수령 방식이 항상 정답은 아닙니다.</p><p>결과는 선택한 미션의 달성 여부와 별 조건을 보여줍니다. IRP 잔액 증가율에는 입출금이 포함되고 납입 제외 운용수익률은 따로 표시됩니다.</p><p>복기에서는 3·6·9턴 분기로 돌아갈 수 있습니다. 미래를 본 연습이므로 최고 기록·완주 보상에 반영하지 않습니다. 새 판·같은 시드 재도전은 시작 조건을 다시 확인합니다.</p>`)+
section('help','저장과 도움말',`<p>진행은 현재 브라우저에 저장됩니다. 새로고침 후 「이어서 플레이」를 선택하세요. 새 판을 최종 시작하면 기존 진행을 대체합니다. 브라우저 저장을 삭제하면 기록을 잃을 수 있습니다.</p><p>효과음이 들리지 않으면 설정의 효과음 테스트와 기기 음량·탭 음소거를 확인하세요. 시장 상세의 「상세 보기」를 열어 이번 보유분 영향과 일반 시장 예시를 구분할 수 있습니다.</p><a href="./learning-guide.html">25문항·공통 기준·공식 근거</a> · <a href="./manual-archive/user-v1.6.1.html">이전 버전 안내</a>`);
writeFileSync('public/user-manual.html',page('연금로드 v1.7.0 · 사용자 안내',`<p>성향을 알고 시작해, 시장을 보고 판단하는 12턴.</p>${user}`));
const operator=
section('scope','적용 범위와 콘텐츠 기준',`<p>v1.7.0 P1: 시작 준비·거래 미리보기·만기 표시·포트폴리오·선택 학습·마감 안내. 금융 상수·세금·점수·시장 생성은 보존합니다. 콘텐츠 버전 ${CONTENT_VERSION}, 확인일 ${CONTENT_REVIEWED_AT}.</p><p><code>src/data/learning-rules.ts</code>의 규칙 ID가 실제 원리·게임 가정·출처 범위를 연결하고 25문항과 화면·생성 문서에서 재사용됩니다. 실제 상품별 영업일·약관을 공통 게임 시간표로 단정하지 않습니다.</p><p><a href="./learning-guide.html">공통 규칙과 25문항 검수표</a>. 해외 자료는 일반 투자 원리만 뒷받침합니다. 도입 보도자료는 당시 원리의 근거이며 현행 적격성을 인증하지 않습니다.</p>`)+
section('save','진행 저장과 호환',`<p>진행 키 <code>pension-road-play-c1</code>, c3 거래 모형. 기존 c1/c2 진행은 기존 계산 규칙으로 복원합니다. 성향 진단 확인 정보와 선택 학습 흐름은 선택 필드로 검증하고 누락된 기존 정보를 추정하지 않습니다.</p><p>새 게임 준비 중에는 기존 진행과 설정을 덮어쓰지 않습니다. 최종 시작에서 확정하며 이어하기는 기존 성향·미션·납입 규칙을 유지합니다. 이전 퀴즈/마무리 큐는 중복 보상 없이 복원합니다.</p><p>오류 재현에는 버전·시드·미션·성향·턴·선택 순서와 복기 JSON을 사용합니다. 학습 효과 측정은 실제 참가자 사전/사후 동형 문항과 추후 검사를 별도로 수행하며, 자동 테스트를 실제 학습 효과로 해석하지 않습니다.</p>`)+
section('qa','운영 확인 순서',`<ol><li>처음 진단, 저장 성향 확인, 재진단 뒤 옵션 재선택, 준비 취소·새로고침, 주간 고정 조건.</li><li>두 행동에서 납입 200만원 합산, 납입 뒤 일반/옵션 매수, 미결제 현금 구분.</li><li>펀드 매수·매도·교체·리밸런싱, 예금 중도해지·만기, 직접/옵션 출처 보존.</li><li>X·포트폴리오 왕복·입력·스크롤 보존. 새로고침 후 퀴즈와 정산 중복 실행 방지.</li><li>12턴 마지막 주문 → 마감 정산 → 수령 비교 → 결과. 수령 재선택의 완주 횟수·주문 보존.</li><li>320/390/768/1440px, 확대·가로 화면·키보드·동작 줄이기, 보드 24칸 이동 일치.</li></ol>`)+
section('history','이전 규칙과 개발 자료',`<p>과거 자동 균등 매수·성향 즉시 변경·이전 별 조건은 당시 저장 참고용입니다. 현재 플레이 방법은 사용자 안내를 따릅니다.</p><a href="./manual-archive/operator-v1.6.1.html">v1.6.1 이하 운영 기록·QA 표</a> · <a href="./manual-archive/user-v1.6.1.html">이전 사용자 안내</a> · <a href="./diagrams/">구조·순서도</a> · <a href="./submission-handoff.html">개발 인수인계</a>`);
writeFileSync('public/operator-manual.html',page('연금로드 v1.7.0 · 운영자 안내',operator));
